name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # 更新内容

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: '機能強化'
    label: 'enhancement'
  - title: '新機能'
    label: 'feature'
  - title: 'Bug修正'
    label: 'bug'
  - title: 'メンテナンス'
    label: 'maintenance'
  - title: 'Documentation'
    label: 'docs'
  - title: '依存関係の更新'
    label: 'dependencies'
